import {test,after,before} from 'node:test';
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
let mf,db;
const origin='https://strunika.test';
const draft={title:'Проверка',tempo:90,loop:true,tone:'balanced',bars:[{chord:'Am',frets:[-1,0,2,2,1,0],mode:'pick',pattern:['rest'],notes:[[{s:1,f:0}]],percussion:[['kick']],changes:[]}]};
async function call(path,{method='GET',body,cookie,originHeader=origin,headers={}}={}){return mf.dispatchFetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(method==='GET'?{}:{'Content-Type':'application/json','X-Strunika-Request':'1',Origin:originHeader}),...headers},body:body===undefined?undefined:JSON.stringify(body)});}
const cookies=response=>response.headers.get('set-cookie')?.split(';')[0];
before(async()=>{mf=new Miniflare({modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-05-15',d1Databases:['DB']});db=await mf.getD1Database('DB');for(const name of(await readdir('drizzle')).filter(x=>x.endsWith('.sql')).sort())for(const statement of(await readFile('drizzle/'+name,'utf8')).split('--> statement-breakpoint').filter(x=>x.trim()))await db.prepare(statement).run();});
after(async()=>{await mf?.dispose();});
test('registration, login, ownership, revision conflict, persistence and logout',async()=>{
 let r=await call('/api/compositions');assert.equal(r.status,401);
 r=await call('/api/account/register',{method:'POST',body:{login:'guitarist',password:'short'}});assert.equal(r.status,400);
 r=await call('/api/account/register',{method:'POST',body:{login:'Guitarist',password:'long secure password 123'}});assert.equal(r.status,201,await r.clone().text());const a=cookies(r),user=(await r.json()).user;assert.equal(user.login,'guitarist');assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal(user.password_hash,undefined);
 const row=await db.prepare('SELECT password_hash FROM users WHERE id=?').bind(user.id).first();assert.match(row.password_hash,/^scrypt:/);assert.ok(!row.password_hash.includes('long secure'));
 r=await call('/api/account/register',{method:'POST',body:{login:'guitarist',password:'another secure password'}});assert.equal(r.status,409);
 r=await call('/api/account/login',{method:'POST',body:{login:'guitarist',password:'wrong'}});assert.equal(r.status,401);
 r=await call('/api/account/login',{method:'POST',body:{login:'missing_user',password:'wrong'}});assert.equal(r.status,401);
 r=await call('/api/account/me',{cookie:a});assert.equal((await r.json()).user.id,user.id);
 const id=crypto.randomUUID();r=await call('/api/compositions',{method:'POST',cookie:a,body:{id,data:{...draft,authorId:'spoof'}}});assert.equal(r.status,201,await r.clone().text());assert.equal((await r.json()).author,'guitarist');
 r=await call('/api/compositions/'+id,{cookie:a});const doc=await r.json();assert.deepEqual(doc.data,draft);assert.equal(doc.revision,1);
 r=await call('/api/compositions',{cookie:a});assert.equal((await r.json()).compositions.length,1);
 r=await call('/api/compositions',{method:'POST',cookie:a,body:{id,data:draft}});assert.equal(r.status,200);
 r=await call('/api/compositions/'+id,{method:'PUT',cookie:a,body:{revision:1,data:{...draft,title:'Версия 2'}}});assert.equal(r.status,200);
 r=await call('/api/compositions/'+id,{method:'PUT',cookie:a,body:{revision:1,data:{...draft,title:'Устаревшая'}}});assert.equal(r.status,409);
 r=await call('/api/account/register',{method:'POST',body:{login:'second_author',password:'a second secure password'}});assert.equal(r.status,201);const b=cookies(r);
 r=await call('/api/compositions',{cookie:b});assert.equal((await r.json()).compositions.length,0);
 r=await call('/api/compositions/'+id,{cookie:b});assert.equal(r.status,404);
 r=await call('/api/compositions/'+id,{method:'PUT',cookie:b,body:{revision:2,data:draft}});assert.equal(r.status,404);
 r=await call('/api/compositions/'+id,{method:'DELETE',cookie:b,body:{revision:2}});assert.equal(r.status,409);
 r=await call('/api/compositions/'+id,{cookie:a});assert.equal((await r.json()).data.title,'Версия 2');
 r=await call('/api/compositions',{method:'POST',cookie:a,body:{id:crypto.randomUUID(),data:draft},originHeader:'https://evil.test'});assert.equal(r.status,403);
 r=await call('/api/compositions',{method:'POST',cookie:a,body:{id:crypto.randomUUID(),data:draft},headers:{'X-Strunika-Request':'wrong'}});assert.equal(r.status,403);
 r=await call('/api/compositions',{method:'POST',cookie:a,body:{id:crypto.randomUUID(),data:{...draft,bars:[{...draft.bars[0],notes:[[{s:99,f:0}]]}]}}});assert.equal(r.status,400);
 r=await call('/api/account/logout',{method:'POST',cookie:a,body:{}});assert.equal(r.status,200);
 r=await call('/api/account/me',{cookie:a});assert.equal((await r.json()).user,null);
 r=await call('/api/account/login',{method:'POST',body:{login:'GUITARIST',password:'long secure password 123'}});assert.equal(r.status,200);const next=cookies(r);assert.notEqual(next,a);
 r=await call('/api/compositions/'+id,{cookie:next});assert.equal((await r.json()).revision,2);
 r=await call('/api/compositions/'+id,{method:'DELETE',cookie:next,body:{revision:2}});assert.equal(r.status,200);
 r=await call('/api/compositions/'+id,{cookie:next});assert.equal(r.status,404);
});
test('assets and auth rate limiting',async()=>{let r=await call('/');assert.equal(r.status,200);assert.match(await r.text(),/authDialog/);r=await call('/library.js');assert.equal(r.status,200);r=await call('/api/account/login',{method:'POST',body:{login:'rate_test',password:'bad'}});assert.equal(r.status,401);let blocked=false;for(let i=0;i<18;i++){r=await call('/api/account/login',{method:'POST',body:{login:'rate_test',password:'bad'}});if(r.status===429){blocked=true;break;}}assert.ok(blocked);});
