import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {composition} from '../server/validation.js';
const guest={title:'Старый черновик',tempo:90,loop:true,tone:'balanced',bars:[{chord:'Am',frets:[-1,0,2,2,1,0],mode:'pick',pattern:['rest'],notes:[[]]}]};
function harness(){const nodes=new Map(),storage=new Map([['six-strings-v1',JSON.stringify(guest)]]),events=new Map();let data=structuredClone(guest),account=null;const docs=new Map();const element=()=>({textContent:'',value:'',hidden:false,disabled:false,open:false,children:[],classList:{toggle(){}},setAttribute(){},append(...v){this.children.push(...v)},replaceChildren(...v){this.children=v},showModal(){this.open=true},close(){this.open=false},focus(){}});const $=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id)};
 const window={Strunika:{getData:()=>structuredClone(data),setData:d=>{data=structuredClone(d);storage.set(window.strunikaDraftKey||'six-strings-v1',JSON.stringify(d));events.get('strunika:changed')?.();},newData:()=>({...structuredClone(guest),title:'Новая композиция'})},addEventListener:(name,fn)=>events.set(name,fn)};
 const fetch=async(path,options)=>{const body=options.body?JSON.parse(options.body):null;const response=(obj,status=200)=>({ok:status<400,status,json:async()=>obj});if(path==='/api/account/me')return response({user:account});if(path==='/api/account/login'){account={id:body.login,login:body.login};return response({user:account});}if(path==='/api/account/logout'){account=null;return response({ok:true});}if(!account)return response({error:'Войди'},401);if(path==='/api/compositions'&&options.method==='GET')return response({compositions:[...docs.values()].filter(d=>d.owner===account.id).map(d=>({id:d.id,title:d.data.title,revision:d.revision,updated_at:Date.now(),author:account.login}))});if(path==='/api/compositions'&&options.method==='POST'){docs.set(body.id,{id:body.id,data:body.data,owner:account.id,revision:1});return response({id:body.id,revision:1,author:account.login});}const id=path.split('/').pop(),doc=docs.get(id);if(options.method==='PUT'){if(body.revision!==doc.revision)return response({error:'Конфликт версий'},409);doc.data=body.data;doc.revision++;return response({id,revision:doc.revision,author:account.login});}if(options.method==='GET')return response({...doc,author:account.login});return response({ok:true});};
 return {$,storage,docs,window,context:vm.createContext({window,document:{getElementById:$,createElement:element},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},fetch,crypto,console,confirm:()=>true,composition}),edit(title){data.title=title;window.Strunika.setData(data)}};
}
test('guest migration, cloud save, per-account drafts and conflict preservation',async()=>{const h=harness();const source=(await readFile('public/library.js','utf8')).replace("import { composition } from '/validation.js';",'');await vm.runInContext('(async()=>{'+source+'})()',h.context);
 assert.equal(h.$('accountName').textContent,'Без аккаунта');h.$('accountLogin').value='alice';h.$('accountPassword').value='a sufficiently long password';await h.$('authForm').onsubmit({preventDefault(){}});assert.equal(h.window.Strunika.getData().title,guest.title);assert.equal(h.$('accountName').textContent,'@alice');assert.equal(h.$('accountPassword').value,'');
 await h.$('saveCloud').onclick();assert.equal(h.docs.size,1);assert.equal(h.$('saved').textContent,'Сохранено в аккаунте');h.edit('Новый черновик Алисы');await h.$('signOut').onclick();assert.equal(h.window.Strunika.getData().title,guest.title);assert.equal(JSON.parse(h.storage.get('strunika-draft:alice')).title,'Новый черновик Алисы');
 h.$('accountLogin').value='bob';await h.$('authForm').onsubmit({preventDefault(){}});assert.equal(h.window.Strunika.getData().title,guest.title);h.edit('Боб');await h.$('saveCloud').onclick();assert.equal(h.docs.size,2);await h.$('signOut').onclick();h.$('accountLogin').value='alice';await h.$('authForm').onsubmit({preventDefault(){}});assert.equal(h.window.Strunika.getData().title,'Новый черновик Алисы');const alice=[...h.docs.values()].find(d=>d.owner==='alice');alice.revision++;await h.$('saveCloud').onclick();assert.match(h.$('libraryMessage').textContent,/Конфликт/);assert.equal(h.window.Strunika.getData().title,'Новый черновик Алисы');assert.equal(JSON.parse(h.storage.get('six-strings-v1')).title,guest.title);
});
