import assets from 'virtual:assets';
import { composition, credentials, HttpError } from './validation.js';
import { hashPassword,checkPassword,currentUser,createSession,sessionCookie,clearCookie,tokenFrom,digest,rateLimit } from './auth.js';
const LIVE_ORIGIN='https://six-strings-workshop.jester-on-1993.chatgpt.site';
const security={'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Cache-Control':'no-store'};
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...security,'Content-Type':'application/json; charset=utf-8',...extra}});
const uuid=value=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
function mutationCheck(request){if(request.headers.get('X-Strunika-Request')!=='1'||!request.headers.get('Content-Type')?.startsWith('application/json'))throw new HttpError(403,'Недопустимый запрос.');const origin=request.headers.get('Origin');const expected=new URL(request.url).origin;if(origin!==expected&&origin!==LIVE_ORIGIN)throw new HttpError(403,'Недопустимый источник запроса.');if(request.headers.get('Sec-Fetch-Site')==='cross-site')throw new HttpError(403,'Недопустимый источник запроса.');}
async function readBody(request){if(Number(request.headers.get('Content-Length'))>400000)throw new HttpError(413,'Композиция слишком большая.');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'Пустой запрос.');let size=0,parts=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>400000){await reader.cancel();throw new HttpError(413,'Композиция слишком большая.');}parts.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}try{const value=JSON.parse(new TextDecoder().decode(bytes));if(!value||Array.isArray(value)||typeof value!=='object')throw Error();return value;}catch{throw new HttpError(400,'Некорректный JSON.');}}
async function api(request,env,context){const db=env.DB;if(!db)throw new HttpError(503,'База данных временно недоступна.');const path=new URL(request.url).pathname,method=request.method;let body;if(!['GET','HEAD'].includes(method)){mutationCheck(request);body=await readBody(request);}
  if(method==='GET'&&path==='/api/account/me')return json({user:await currentUser(request,db)});
  if(method==='POST'&&['/api/account/register','/api/account/login'].includes(path)){
    const register=path.endsWith('/register'),{login,password}=credentials(body,register),ip=request.headers.get('CF-Connecting-IP')||'unknown';
    await rateLimit(db,'auth-ip:'+ip,30,15*60*1000);await rateLimit(db,'auth-login:'+login,15,15*60*1000);
    context?.waitUntil(db.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(Date.now()).run().catch(()=>{}));
    let user=await db.prepare('SELECT id,login,password_hash FROM users WHERE login=?').bind(login).first();
    if(register){if(user)throw new HttpError(409,'Этот логин уже занят.');const id=crypto.randomUUID(),hash=await hashPassword(password);try{await db.prepare('INSERT INTO users(id,login,password_hash,created_at) VALUES(?,?,?,?)').bind(id,login,hash,Date.now()).run();}catch(error){if((await db.prepare('SELECT id FROM users WHERE login=?').bind(login).first()))throw new HttpError(409,'Этот логин уже занят.');throw error;}user={id,login};}
    else if(!await checkPassword(password,user?.password_hash))throw new HttpError(401,'Неверный логин или пароль.');
    const previous=tokenFrom(request);if(previous)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(previous)).run();
    const token=await createSession(db,user.id);return json({user:{id:user.id,login:user.login}},register?201:200,{'Set-Cookie':sessionCookie(token)});
  }
  if(method==='POST'&&path==='/api/account/logout'){const token=tokenFrom(request);if(token)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();return json({ok:true},200,{'Set-Cookie':clearCookie()});}
  const user=await currentUser(request,db);if(!user)throw new HttpError(401,'Войди в аккаунт, чтобы открыть библиотеку.');
  if(method!=='GET')await rateLimit(db,'write:'+user.id,120,60*1000);
  if(path==='/api/compositions'&&method==='GET'){const rows=await db.prepare('SELECT id,title,revision,created_at,updated_at FROM compositions WHERE author_id=? ORDER BY updated_at DESC LIMIT 200').bind(user.id).all();return json({compositions:rows.results.map(row=>({...row,author:user.login}))});}
  if(path==='/api/compositions'&&method==='POST'){
    if(!uuid(body.id))throw new HttpError(400,'Некорректный идентификатор.');const data=composition(body.data),encoded=JSON.stringify(data),now=Date.now();
    const previous=await db.prepare('SELECT id,author_id,revision,data FROM compositions WHERE id=?').bind(body.id).first();
    if(previous){if(previous.author_id===user.id&&previous.data===encoded)return json({id:previous.id,revision:previous.revision,author:user.login});throw new HttpError(409,'Не удалось создать копию. Повтори сохранение.');}
    const row=await db.prepare('INSERT INTO compositions(id,author_id,title,data,revision,created_at,updated_at) SELECT ?,?,?,?,1,?,? WHERE (SELECT count(*) FROM compositions WHERE author_id=?)<200 RETURNING id,revision').bind(body.id,user.id,data.title,encoded,now,now,user.id).first();if(!row)throw new HttpError(409,'В библиотеке уже 200 композиций.');return json({...row,author:user.login},201);
  }
  const match=path.match(/^\/api\/compositions\/([a-f0-9-]+)$/i);if(match&&uuid(match[1])){
    const id=match[1];
    if(method==='GET'){const row=await db.prepare('SELECT id,data,revision,created_at,updated_at FROM compositions WHERE id=? AND author_id=?').bind(id,user.id).first();if(!row)throw new HttpError(404,'Композиция не найдена.');return json({...row,data:JSON.parse(row.data),author:user.login});}
    if(method==='PUT'){if(!Number.isInteger(body.revision)||body.revision<1)throw new HttpError(400,'Некорректная версия.');const data=composition(body.data);const row=await db.prepare('UPDATE compositions SET title=?,data=?,revision=revision+1,updated_at=? WHERE id=? AND author_id=? AND revision=? RETURNING id,revision').bind(data.title,JSON.stringify(data),Date.now(),id,user.id,body.revision).first();if(!row){const exists=await db.prepare('SELECT id FROM compositions WHERE id=? AND author_id=?').bind(id,user.id).first();throw new HttpError(exists?409:404,exists?'Композиция изменена в другой вкладке. Сохрани копию или открой свежую версию.':'Композиция не найдена.');}return json({...row,author:user.login});}
    if(method==='DELETE'){if(!Number.isInteger(body.revision))throw new HttpError(400,'Некорректная версия.');const row=await db.prepare('DELETE FROM compositions WHERE id=? AND author_id=? AND revision=? RETURNING id').bind(id,user.id,body.revision).first();if(!row)throw new HttpError(409,'Композиция уже удалена или изменена. Обнови библиотеку.');return json({ok:true});}
  }
  throw new HttpError(404,'Не найдено.');
}
export default {async fetch(request,env,context){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await api(request,env,context);if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});const path=url.pathname==='/'?'/index.html':url.pathname;const content=assets[path];if(content===undefined)return new Response('Not found',{status:404});const type=path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html';return new Response(request.method==='HEAD'?null:content,{headers:{...security,'Content-Type':type+'; charset=utf-8','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; media-src 'self' blob:; object-src 'none'; base-uri 'none'; form-action 'self'"}});}catch(error){if(error instanceof HttpError)return json({error:error.message},error.status);console.error('Strunika request failed',error?.name||'Error');return json({error:'Сервер временно недоступен. Изменения остались в черновике; попробуй ещё раз.'},503);}}};
